version: '3.8'
services:
  debugger:
    build:
      context: ./
      target: production
    volumes:
      - ./config.json:/app/config.json
    command: npm run start
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production